# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fdec446701f9766f6f2f3b84794a45bb3db35846b596d3b8c6e9dee43ec3ac4ab0a713a72ce7fac29011e7d64d513c1bfd45e07d77c27fbf412b42613561149

test:
  secret_key_base: 620ec2ca4990dc2dd7461117b0215938a4b8737cdd2bb1c5d78434292b2e7bc18428f37febf6afe0c4b1414928699abcac0ebc3fe8e431b0d9bf0327b43f7658

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
